### PR TITLE
Generate the SDK for Ubports

### PR DESCRIPTION
**Pull request by mardy**

### CODE REVIEW

**Comment by Flohack74** [comment]
@mardy Is this of importance? Also your commit messages are strange ;)

**Comment by mardy** [comment]
Hi @Flohack74, yes this is still important but it's not ready to be merged yet. I've marked it as a work in progress (I needed to create a merge request in order to have my branch built by Jenkins).

Anyway, this is a good reminder that I need to finish this :-)

**Review by Flohack74 — DISMISSED** [review]
On hold as per @mardy

**Comment by Flohack74** [comment]
You will tell us when its ready right?

**Comment by mardy** [comment]
I'm testing it and it's working (save for hash sums mismatches, which seem to appear and come at random: @mariogrip , can you please check?).

But you can already review the changes, and we can even merge them (the only thing that can break at the moment is `crossbuilder`, but I guess I'm the only one using it :-D

**Pull request merged**
